# Generated by Django 5.0.3 on 2024-03-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver_username',
            field=models.CharField(default='ghj', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=10),
        ),
    ]
