# Generated by Django 5.0.3 on 2024-03-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmaapp', '0002_ride_driver_username_alter_userprofile_fuel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver_username',
        ),
    ]
